# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json

# See GitHub's documentation for more information on this file:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: daily
    commit-message:
      prefix: ci
      include: scope
    labels:
      - "deps/github-actions"
      - dependencies
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: build
      prefix-development: chore
      include: scope
    labels:
      - "deps/devcontainer"
      - dependencies
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: gomod
    directory: /quickstarts/401-testing-terratest
    schedule:
      interval: daily
    commit-message:
      prefix: build
      prefix-development: chore
      include: scope
    labels:
      - "deps/go"
      - dependencies
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: terraform
    directories:
      - "/quickstarts/*"
    schedule:
      interval: daily
    commit-message:
      prefix: build
      prefix-development: chore
      include: scope
    labels:
      - "deps/terraform"
      - dependencies
    groups:
      all:
        patterns: ["*"]
