#  yaml-language-server: $schema=https://taskfile.dev/schema.json
# docs: https://taskfile.dev
---
version: "3"

includes:
  internal: internal.yml

tasks:
  # * Tools
  tools:
    desc: Install Security tools
    cmds:
      - for: [Gitleaks.Gitleaks]
        task: internal:install:winget
        vars:
          APP: "{{.ITEM}}"
        platforms: [windows]
      - for: [gitleaks]
        task: internal:install:brew
        vars:
          APP: "{{.ITEM}}"
        platforms: [darwin]
      - cmd: |
          arch=$(uname -m)
          if [[ "${arch}" == "x86_64" ]]; then
            arch="x64"
          elif [[ "${arch}" == "aarch64" ]]; then
            arch="arm64"
          else
            echo "Unsupported architecture: ${arch}"
            exit 1
          fi
          download_url=$(curl --location --silent "https://api.github.com/repos/gitleaks/gitleaks/releases/latest" | grep 'browser_download_url.*gitleaks.*linux_'"${arch}"'.*tar.gz"' | grep -o 'https://[^"]*')
          curl --location -o /tmp/gitleaks.tar.gz "${download_url}"
          tar -xf /tmp/gitleaks.tar.gz --directory /tmp
          rm /tmp/gitleaks.tar.gz
          sudo mv /tmp/gitleaks /usr/local/bin/gitleaks
        platforms: [linux]
      - for: [checkov]
        task: internal:install:pipx
        vars:
          APP: "{{.ITEM}}"

  # * Lint
  lint:
    desc: Run Security linters
    cmds:
      - gitleaks detect --source . --redact=90 --verbose
      # - checkov --quiet --download-external-modules true --directory . #TODO
    dir: "{{.ROOT_DIR}}"
