# yaml-language-server: $schema=https://raw.githubusercontent.com/DavidAnson/markdownlint/main/schema/markdownlint-config-schema.json
---
# Markdownlint YAML configuration
# Default source: https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# Default state for all rules
default: true

# Path to configuration file to extend
# extends: null

# MD013/line-length - Line length
MD013: false

# MD024/no-duplicate-heading
MD024: false

# MD025/single-title - Single title
MD025:
  front_matter_title: ""

# MD033/no-inline-html - Inline HTML
MD033:
  # Allowed elements
  allowed_elements: ["br", "pre"]

# MD041/first-line-heading/first-line-h1
MD041: false

# MD046/code-block-style - Code block style
MD046:
  # Block style
  style: "fenced"

# MD060/table-column-style - Table column style
MD060: false
