#  yaml-language-server: $schema=https://taskfile.dev/schema.json
# docs: https://taskfile.dev
#
# --- Windows ---
# winget install Task.Task
#
# --- Linux ---
# sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
# echo 'command -v task >/dev/null || export PATH="$PATH:$HOME/.local/bin"' >> ~/.profile
# source ~/.profile
#
# ---  macOS ---
# brew install go-task/tap/go-task
---
version: "3"

includes:
  internal:
    taskfile: .taskfiles/internal.yml
  gh:
    taskfile: .taskfiles/github.yml
  go:
    taskfile: .taskfiles/golang.yml
  md:
    taskfile: .taskfiles/markdown.yml
  sec:
    taskfile: .taskfiles/security.yml
  spell:
    taskfile: .taskfiles/spell.yml
  tf:
    taskfile: .taskfiles/terraform.yml
  yml:
    taskfile: .taskfiles/yaml.yml

vars:
  REPO_ABS_ROOT_PATH:
    sh: git rev-parse --show-toplevel

tasks:
  default:
    desc: Default task
    cmds:
      - task --list

  tools:
    desc: Install tools
    cmds:
      - task: gh:tools
      - task: go:tools
      - task: md:tools
      - task: sec:tools
      - task: spell:tools
      - task: tf:tools
      - task: yml:tools

  lint:
    desc: Lint files
    cmds:
      - task: gh:lint
      - task: go:lint
      - task: sec:lint
      - task: tf:lint
      - task: yml:lint
      - task: md:lint
      - task: spell:lint

  docs:
    desc: Generate documentation
    cmds:
      - task: tf:docs
      - task: md:lint
      - task: spell:lint
