output "string" {
  value       = random_string.this.result
  description = "Random string generated by the random_string resource"
}

output "uuid" {
  value       = random_uuid.this.result
  description = "Random UUID generated by the random_uuid resource"
}

output "password" {
  value       = random_password.this.result
  sensitive   = true
  description = "Random password generated by the random_password resource"
}
